"""initial_schema

Revision ID: 42f833fa7fd6
Revises: 
Create Date: 2026-08-17 23:36:49.351109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = '42f833fa7fd6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('organization_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('organization_id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('endpoints',
    sa.Column('endpoint_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('organization_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('os_name', sa.String(length=100), nullable=True),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('architecture', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('endpoint_id')
    )
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.create_index('ix_endpoints_org_hostname', ['organization_id', 'hostname'], unique=False)
        batch_op.create_index('ix_endpoints_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_endpoints_organization_id'), ['organization_id'], unique=False)

    op.create_table('users',
    sa.Column('user_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('organization_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index('ix_users_org_role', ['organization_id', 'role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('collectors',
    sa.Column('collector_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('organization_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('endpoint_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('collector_name', sa.String(length=255), nullable=True),
    sa.Column('collector_version', sa.String(length=50), nullable=True),
    sa.Column('enrollment_token_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('credential_hash', sa.String(length=255), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.endpoint_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collector_id')
    )
    with op.batch_alter_table('collectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collectors_credential_hash'), ['credential_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_collectors_endpoint_id'), ['endpoint_id'], unique=False)
        batch_op.create_index('ix_collectors_endpoint_status', ['endpoint_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_collectors_enrollment_token_hash'), ['enrollment_token_hash'], unique=False)
        batch_op.create_index('ix_collectors_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_collectors_organization_id'), ['organization_id'], unique=False)

    op.create_table('events',
    sa.Column('event_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('organization_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('collector_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('endpoint_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_source', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_category', sa.String(length=100), nullable=False),
    sa.Column('event_id_external', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('process_name', sa.String(length=500), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('command_line', sa.Text(), nullable=True),
    sa.Column('source_ip', sa.String(length=100), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('destination_ip', sa.String(length=100), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('raw_log', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collector_id'], ['collectors.collector_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.endpoint_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_collector_id'), ['collector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_endpoint_id'), ['endpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_category'), ['event_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_hostname'), ['hostname'], unique=False)
        batch_op.create_index('ix_events_org_category', ['organization_id', 'event_category'], unique=False)
        batch_op.create_index('ix_events_org_endpoint', ['organization_id', 'endpoint_id'], unique=False)
        batch_op.create_index('ix_events_org_severity', ['organization_id', 'severity'], unique=False)
        batch_op.create_index('ix_events_org_timestamp', ['organization_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_source_ip'), ['source_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_username'))
        batch_op.drop_index(batch_op.f('ix_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_events_source_ip'))
        batch_op.drop_index(batch_op.f('ix_events_severity'))
        batch_op.drop_index(batch_op.f('ix_events_organization_id'))
        batch_op.drop_index('ix_events_org_timestamp')
        batch_op.drop_index('ix_events_org_severity')
        batch_op.drop_index('ix_events_org_endpoint')
        batch_op.drop_index('ix_events_org_category')
        batch_op.drop_index(batch_op.f('ix_events_hostname'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_events_event_category'))
        batch_op.drop_index(batch_op.f('ix_events_endpoint_id'))
        batch_op.drop_index(batch_op.f('ix_events_collector_id'))

    op.drop_table('events')
    with op.batch_alter_table('collectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collectors_organization_id'))
        batch_op.drop_index('ix_collectors_org_status')
        batch_op.drop_index(batch_op.f('ix_collectors_enrollment_token_hash'))
        batch_op.drop_index('ix_collectors_endpoint_status')
        batch_op.drop_index(batch_op.f('ix_collectors_endpoint_id'))
        batch_op.drop_index(batch_op.f('ix_collectors_credential_hash'))

    op.drop_table('collectors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index('ix_users_org_role')
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_endpoints_organization_id'))
        batch_op.drop_index('ix_endpoints_org_status')
        batch_op.drop_index('ix_endpoints_org_hostname')

    op.drop_table('endpoints')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
